### ISSUE TITLE
How to "run" my bot.

### ISSUE THREAD

**Issue by pranaymk** [seishun/node-steam-trade#27]
I have worked on a basic bot and have a steam account setup to try it on but I can't figure out how to run it. I have tried a .bat to launch it and get an error "Cannot find module 'steam'.

Some help would be greatly appreciated.

**Comment by redlive13** [comment]
seishun hello im seeing you have alot of experience programing its a old post but help me with something if possible

connected
Invalid login/password, or allready logged.
Connection closed
Trying to reconnect
connected
Invalid login/password, or allready logged.
Connection closed
Trying to reconnect
connected
Invalid login/password, or allready logged.
Connection closed
Trying to reconnect
connected

(all the times i turn on pc again it happens i cant disconnect my bot in somewher my bot is working on my pc weird i dont understand login and password is the same it works fine but sometimes it happens
