### ISSUE TITLE
Items are exchanged but end with 'pending'

### ISSUE THREAD

**Issue by pmk010** [seishun/node-steam-trade#55]
I've been running into an issue where with both people having trade confirmations disabled, upon completion of a trade, items are exchanged but the trade ends with 'pending'. A trade offer is created with "Items Now Unavailable For Trade".

Has anyone got a fix for this? Or is it just a valve issue that I may just have to create a dirty workaround for?

**Comment by seishun** [comment]
That's how trades currently work. Try it yourself. If you're the one who initiated the trade, on completion you get window with a trade offer with "Items Now Unavailable For Trade".

**Comment by seishun** [comment]
I think in this case the only way to get the list of received items would be to parse the HTML with the new item notification in your inventory.

**Comment by pmk010** [comment]
Or alternatively, since you still receive a trade offer id, you could check the trade offer's contents? But that's outside the scope of this module.
