### ISSUE TITLE
themAssets is null

### ISSUE THREAD

**Issue by JakeCooper** [seishun/node-steam-trade#56]
I'm trying to observe the other parties assets, however the array seems to be empty.

http://pastebin.com/vdxDWAWH

Not sure if anyone else has observed it.

EDIT: It seems that I the themAssets array isn't being updated. Interesting.

EDIT2: Seems calling it during the .on('ready') event gets the array. I'm gonna leave the question up as I'd like to know if there's a way to properly grab it during the .on('offerchanged') event.

**Comment by seishun** [comment]
So null or empty?

**Comment by seishun** [comment]
themAssets is updated, but only after the event is emitted, so you get the previous state. Is there really an issue, considering that you already know which item was added or removed?

**Comment by JakeCooper** [comment]
Yea the array is empty. I guess so, It might just be nice if it wasn't one trade 'motion' behind.

Doesn't matter for my purposes, I can just get themAssets on ready.

**Comment by seishun** [comment]
Generally, when there is a property and an event that fires when the property changes, I update the property _after_ the event fires, giving the user a chance to inspect the old value. It might not be useful in this case, but changing the behavior would involve a major rework in the event handling logic for questionable benefit.
