### ISSUE TITLE
How do I run a trade bot if I get steam guarded every time I restart the bot?

### ISSUE THREAD

**Issue by Gacnt** [seishun/node-steam-trade#58]
As the title says, every time I log in with the bot I get a new Steam Guard code and have to re-login and re-auth code and then I get steam guard trade banned for 7 days.. Is there a way to avoid this?

**Comment by seishun** [comment]
Not a node-steam-trade issue. Steam Guard's behavior is described [here](https://github.com/seishun/node-steam#logonlogondetails).
