### ISSUE TITLE
How can I setup email confirmation?

### ISSUE THREAD

**Issue by Gacnt** [seishun/node-steam-trade#60]
I have read through the other issue, and I understand that you've added a pending condition which is fantastic, and guys were saying to poll steamcommunity.com/trade/id/receipt/ but mine stays at `success:false` no matter if I accept or cancel the trade so I'm not able to finalize the trade on the bots end. Can you please tell me how to properly handle it?
```
function emailConfirmationPoll(tradeID) {
    console.log('New Email Confirmation');
    var x = 0;
    var poll = setInterval(function() {
        http.get('http://steamcommunity.com/trade/' + tradeID + '/receipt/', function(res) {
            var body = '';
            
            res.on('data', function(chunk) {
                body += chunk;
            });
            res.on('end', function() {
                var status = JSON.parse(body);
                if (status.success === true) {
                    console.log(body);
                    clearInterval(poll)
                    console.log(poll);
                }
                console.log(body, x);
            })
            
           
        });
        x++;
        if (x === 20) {
            console.log('Poll Stopped')
            clearInterval(poll);
        }
    }, 10000)
    
}
```

This is a quick version of what I have so far

**Comment by seishun** [comment]
Who told you to poll? You have a trade offer ID, there is no "trade receipt" for it. Use trade offer functionality to get its status.

Anyway, what happens after the trade is over is outside the scope of this library.
