### ISSUE TITLE
After sending trade offer my bot crashes

### ISSUE THREAD

**Issue by TMGMilkyx** [seishun/node-steam-trade#63]
I can run my bot fine until i sent it a trade offer. As soon as i accept the email verification and my bot gets the trade request it crashes and gives this error.

http://gyazo.com/8f977b440ad8d75f5e0be698bf89b91e

Any help would be appreciated.

**Comment by Ax6** [comment]
As mentioned earlier this is not "my bot doesn't work, what to do?" help center. Unless your problems have to do with node-steam-trade and they actually have a cause related to this module, this is not the right place to ask.
Your problem is clearly related to mysql, probably a wrong query, node-steam-trade is completely unrelated

**Comment by seishun** [comment]
What's with all the MySQL "issues" lately?

**Comment by TMGMilkyx** [comment]
I'm sorry about the questions lately and them being sql related. I ask in other forums reddits etc but thr people there don't know and you guys seem to be the only ones who can assist me.

**Comment by cymruu** [comment]
They dont "dont know" but you didnt even prove that you tried to solve your problem by yourself. Your SQL query returns no data so the row is not set.

**Comment by TMGMilkyx** [comment]
@cymruu Sorry if it seems as if im not trying but i am, im just not that experienced with javascript and SQL. You say my query returns no data so the row needs to be set, does that mean the table it's trying to read from has already been set?

**Comment by cymruu** [comment]
@TMGMilkyx i would need see the code, query and database to say more. At the moment i can say that row[0] is undefined so when you try to do something with this, your script crashes becouse there is no such variable

**Comment by TMGMilkyx** [comment]
@cymruu 

The code: http://pastebin.com/znC9Fasj

Tables inside the databse: http://gyazo.com/07db543e777685b10f839324d39d094a

I don't really know what you meant by query. Hope this can help make more sense, if you need anything else i will be happy to prove it.

**Comment by cymruu** [comment]
@TMGMilkyx 
```mysql
SELECT `value` FROM `info` WHERE `name`='maxitems' 
```
: 335

**Comment by TMGMilkyx** [comment]
@cymruu Unless i have picked it up wrong it's talking about the info table?

http://gyazo.com/5eca1fa1a2d169aaabf3ec34804a1d56

**Comment by cymruu** [comment]
Yep but please execute the query, click here and paste
![image](https://cloud.githubusercontent.com/assets/2981598/8918120/64758d30-34b6-11e5-9a76-0588d2c30d96.png)

**Comment by TMGMilkyx** [comment]
I got this: http://gyazo.com/e8139cb92db59fc0b845aaca89801c77

**Comment by cymruu** [comment]
@TMGMilkyx told you, query returns no data so the row[0] is empty too

**Comment by TMGMilkyx** [comment]
@cymruu So is there something wrong with the code or do i need to add something to the database

**Comment by cymruu** [comment]
@TMGMilkyx you need to add something 
INSERT INTO `info` VALUES ('maxitems', 10);
Where 10 is the max items you want in raffle, propably. Dunno i didnt code that

**Comment by TMGMilkyx** [comment]
@cymruu I think i could have done it wrong? Is this what you meant?

http://gyazo.com/8dfd91de447838fbcfdae3cc81f8862d

**Comment by cymruu** [comment]
Nope, just execute the query. But i would suggest to start your programming journey with something easier than jackpot site.

**Comment by TMGMilkyx** [comment]
@cymruu Yeah, i agree i was rather ambitious. This is what it returned: http://gyazo.com/318deee64a66789a3058148ded61548c

**Comment by cymruu** [comment]
because you didnt delete the column you added before

**Comment by TMGMilkyx** [comment]
@cymruu I think i did, this is what is shows in the table: http://gyazo.com/c802ff3d36214986c8cb2ad2eff9c8a0

**Comment by andrewda** [comment]
This really isn't a MySQL help forum, and obviously this isn't getting anywhere. There is a very active official forum [here](http://forums.mysql.com/list.php?10) or you can ask the question that you need answered on StackOverflow. Also consider the [MySQL subreddit](https://www.reddit.com/r/MySQL).

**Comment by TMGMilkyx** [comment]
@andrewda Posted on StackOverflow, thanks for the suggestion.

**Comment by seishun** [comment]
Please don't discuss SQL here, all watchers receive notifications about this.
