### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by QPandaQ** [seishun/node-steam-trade#65]
Hi i'm new in working with node but when i tryed to type: npm install git://github.com/seishun/node-steam-trade.git as it was in readme file i got this error(log file):

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\node\\\\node.exe',
1 verbose cli   'D:\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'git://github.com/seishun/node-steam-trade.git' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink D:\node\\node.exe
5 silly cache add args [ 'git://github.com/seishun/node-steam-trade.git', null ]
6 verbose cache add spec git://github.com/seishun/node-steam-trade.git
7 silly cache add parsed spec { raw: 'git://github.com/seishun/node-steam-trade.git',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: 'git://github.com/seishun/node-steam-trade.git',
7 silly cache add   spec: 'git://github.com/seishun/node-steam-trade.git',
7 silly cache add   type: 'git' }
8 verbose addRemoteGit u="git://github.com/seishun/node-steam-trade.git" silent=false
9 silly addRemoteGit normalized { url: 'git://github.com/seishun/node-steam-trade.git',
9 silly addRemoteGit   branch: 'master' }
10 silly addRemoteGit v git-github-com-seishun-node-steam-trade-git-f6890cc9
11 verbose addRemoteGit C:\Users\Panda\AppData\Roaming\npm-cache\_git-remotes\git-github-com-seishun-node-steam-trade-git-f6890cc9 not in flight; cloning
12 warn `git config --get remote.origin.url` returned wrong result (git://github.com/seishun/node-steam-trade.git) undefined
12 warn `git config --get remote.origin.url` returned wrong result (git://github.com/seishun/node-steam-trade.git) undefined
13 verbose gentlyRm vacuuming C:\Users\Panda\AppData\Roaming\npm-cache\_git-remotes\git-github-com-seishun-node-steam-trade-git-f6890cc9
14 silly gentlyRm purging C:\Users\Panda\AppData\Roaming\npm-cache\_git-remotes\git-github-com-seishun-node-steam-trade-git-f6890cc9
15 silly gentlyRm quitting because other entries in C:\Users\Panda\AppData\Roaming\npm-cache\_git-remotes
16 error git clone git://github.com/seishun/node-steam-trade.git undefined
16 error git clone git://github.com/seishun/node-steam-trade.git undefined
17 verbose stack Error: not found: git
17 verbose stack     at F (D:\node\node_modules\npm\node_modules\which\which.js:38:28)
17 verbose stack     at E (D:\node\node_modules\npm\node_modules\which\which.js:41:29)
17 verbose stack     at D:\node\node_modules\npm\node_modules\which\which.js:52:16
17 verbose stack     at FSReqWrap.oncomplete (fs.js:99:15)
18 verbose cwd C:\Users\Panda\Desktop\dupa
19 error Windows_NT 6.1.7601
20 error argv "D:\\node\\\\node.exe" "D:\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "git://github.com/seishun/node-steam-trade.git"
21 error node v0.12.0
22 error npm  v2.5.1
23 error code ENOGIT
24 error not found: git
25 error Failed using git.
25 error This is most likely not a problem with npm itself.
25 error Please check if you have git installed and in your PATH.
26 verbose exit [ 1, true ]

**Comment by seishun** [comment]
> 25 error Please check if you have git installed and in your PATH.

Seems clear to me.

**Comment by QPandaQ** [comment]
Thanks for fast reply  and sorry i didnt see that. But now i have this error:
![19-24-32](https://cloud.githubusercontent.com/assets/14250922/9832714/f02f6052-5983-11e5-9dd9-d16807f7414f.jpg)
I didnt change anything in scrapbank.js, only changed name of file to start.js and my acc name and password.

**Comment by andrewda** [comment]
@QPandaQ You're using the new version of Node-Steam with code designed for version 0.6.8. If you don't want to update the bot, install the old version of Node-Steam with `npm install steam@0.6.8`.
