### ISSUE TITLE
tradeProposed

### ISSUE THREAD

**Issue by QPandaQ** [seishun/node-steam-trade#67]
TradeProposed doesnt work for me. My bot is logged in and when i send him trade offer, nothing happends. 

steam.on('tradeProposed', function(tradeID, otherClient) {
  console.log('tradeProposed' + otherClient);
  steam.respondToTrade(tradeID, true);
});

this is my code as in example. I also noticed that in steam lib 'tradeProposed' emits also 'otherName' '
  this.emit('tradeProposed', tradeProp.tradeRequestId, tradeProp.otherSteamid.toString(), tradeProp.otherName);

but anyway if i change my code to: steam.on('tradeProposed', function(tradeID, otherClient, otherName) it still doesnt work.

**Comment by seishun** [comment]
Wrong repo, your issue is with node-steam, not node-steam-trade. And it looks like you're using an old and unsupported version of node-steam.
