### ISSUE TITLE
Error with inv not being defined? 

### ISSUE THREAD

**Issue by rycao18** [seishun/node-steam-trade#71]
What exactly is wrong here with inv? 

```
var inventory;
var scrap;
var weapons;
var addedScrap;
var client;

steamTrading.on('sessionStart', function(otherClient) {
  inventory = [];
  scrap = [];
  weapons = 0;
  addedScrap = [];
  client = otherClient;
  
  LOG('trading ' + steamFriends.personaStates[client].player_name);
  steamTrade.open(otherClient);
  steamTrade.loadInventory(440, 2, function(inv) {
    inventory = inv;
    scrap = inv.filter(function(item) { return item.name == 'Scrap Metal';});
// console.log(scrap);
  });
});
```

**Comment by seishun** [comment]
This is not a help desk. If there is a problem with `loadInventory`, provide a minimal test case that reproduces the issue.

**Comment by rycao18** [comment]
I took this straight from the test code at https://github.com/seishun/node-steam-trade/blob/master/scrapbank.js 
lines 77-102 so just saying the code given there has some sort of error with inv being undefined

**Comment by andrewda** [comment]
No, it's not a code issue. It works fine for me. Handle the `error` event to see if you're receiving some kind of issue.

**Comment by seishun** [comment]
https://github.com/seishun/node-steam-trade#loadinventoryappid-contextid-callback

>The first argument to callback will be an array of item objects in case of success, otherwise a falsy value. Failure implies that your cookie has expired (see 'error' event).

**Comment by andrewda** [comment]
Yea, my bad, you're right. He should be getting an error instead of `undefined`.

@rycao18 where are you logging `inv`? What code are you using that returns `undefined` when logged? scrapbank.js never actually logs `inv`.

**Comment by rycao18** [comment]
I'm getting error inv is undefined at the line where it attempts to do the
line

scrap = inv.filter(........)

**Comment by seishun** [comment]
>I'm getting error inv is undefined at the line where it attempts to do the line

You should understand what the example code does instead of just using it as a complete solution.

You were already linked to the documentation that clearly explains what it means when `inv` is falsy and how to deal with it.
