### ISSUE TITLE
Items do not show up in trade after bot adds them

### ISSUE THREAD

**Issue by rycao18** [seishun/node-steam-trade#76]
Hello! I am trying to make a bot that live trades with other users. Whenever my bot adds the items into the trade, I cannot see them. I have to ready the trade, then the items will appear. Does anyone know why this is? Does there need to be a delay in between each item being added? Am I adding the items wrong and that is why the items don't show up? The items "show up" in chat, because I can see 7 of the same message, which says "[Bot] rycao18 bot has added Refined Metal". The items just do not show up in the trade at all until I press ready. 

Thanks

Here is my code
`for (var i = 0; i < Math.floor(livetheirScrap/9); i++) {
    steamTrade.addItem(refinedmetal[i]);
}`

**Comment by seishun** [comment]
Can you provide a video?

**Comment by rycao18** [comment]
never mind, it appears the issue has fixed itself. Although, I do have a new issue (whenever I add items, there is a massive delay between the item showing up in my "area" that i'm trading. I will provide video on a new issue and close this issue.

**Comment by seishun** [comment]
> whenever I add items, there is a massive delay between the item showing up in my "area" that i'm trading

This is not a library issue, just Steam servers being slow.

**Comment by rycao18** [comment]
I have gotten the error to occur again. It appears it happens randomly ? Might be a server problem? I am uploading a video now to youtube.

**Comment by seishun** [comment]
If it happens randomly, then it's a server problem. I can't do anything about it.

**Comment by rycao18** [comment]
https://youtu.be/WtOL2qUbQkw

about 1:20 in the video shows this error

**Comment by LidamaoHub** [comment]
I have the same problem,and I tried to loop the "addItem" until the err of callback is true,but the items doesn't show
