### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by arik123** [seishun/node-steam-trade#78]
I have a problem : im using node-steam-user and im unable to send cookies,  it return array of cookies and i dont know what and how to send it.  This is that array:
[ 'sessionid=3c417e41096b69996f00634c',
  'steamLogin=76561198295307456%7c%7c112F1425F6649FD8BF9BC613E83D91DA24DD1A69',
  'steamLoginSecure=76561198295307456%7c%7c614BC55F9828DAC7B61F824FDAE88E41BC6439F4' ]

**Comment by seishun** [comment]
Just call `setCookie` on each of them, see https://github.com/seishun/node-steam-trade#setcookiecookie.

**Comment by arik123** [comment]
i did and it still dont work
