### ISSUE TITLE
Cookies issue

### ISSUE THREAD

**Issue by arik123** [seishun/node-steam-trade#79]
Here is my code: https://pastebin.com/eh9pRYf6  I did everything what is writen in readme and still dont work.  Please tell me what im doing wrong.

**Comment by seishun** [comment]
1. This is not a helpdesk.
2. You can post in closed issues, no need to create a new one.
3. "still dont work" What doesn't work? What are you trying to do?

If you think there's a library issue, please provide a minimal reproducible test case. If not, try asking in https://github.com/steam-forward/node-steam-forum.

**Comment by arik123** [comment]
When i use command trade.open() it send back error 
![image](https://user-images.githubusercontent.com/12786043/27254860-da1be934-5391-11e7-8956-61a022cf9af5.png)
i use this for recieving trade offer 
client.on('tradeRequest', function (steamID, respond) {
    console.log("Incoming trade request from " + steamID.getSteam3RenderedID() + ", accepting");
    respond(false);
    trade.open(steamID, function () {
        trade.addItem(5874114798);
    });
});
 and this : 
client.on('webSession', function (sessionID, cookies) {
    trade.setCookie(cookies[0]);
    console.log(cookies[0]);
    trade.setCookie(cookies[1]);
    console.log(cookies[1]);
    trade.setCookie(cookies[2]);
    console.log(cookies[2]);
});
to set up cookies (you can see both in that code in my first comment)
Where is mistake ? Please help me i know that to this isnt helpdesk but there is none.

**Comment by seishun** [comment]
It seems you didn't set the `sessionID` property as described [here](https://github.com/seishun/node-steam-trade#usage).

**Comment by arik123** [comment]
and how to set it ?

**Comment by seishun** [comment]
`trade.sessionID = yoursessionid`

**Comment by arik123** [comment]
Thanks you
