### ISSUE TITLE
event OfferChanged error

### ISSUE THREAD

**Issue by arik123** [seishun/node-steam-trade#80]
> C:\Users\Max\Desktop\node\bot\node_modules\steam-trade\index.js:208
>       return self._themInventories[item.appid][item.contextid][item.assetid];
>                                               ^
> 
> TypeError: Cannot read property '2' of undefined
>     at C:\Users\Max\Desktop\node\bot\node_modules\steam-trade\index.js:208:47
>     at Array.map (native)
>     at SteamTrade._onTradeStatusUpdate (C:\Users\Max\Desktop\node\bot\node_modules\steam-trade\index.js:206:72)
>     at Request._callback (C:\Users\Max\Desktop\node\bot\node_modules\steam-trade\index.js:244:10)
>     at Request.self.callback (C:\Users\Max\Desktop\node\bot\node_modules\request\request.js:188:22)
>     at emitTwo (events.js:125:13)
>     at Request.emit (events.js:213:7)
>     at Request.<anonymous> (C:\Users\Max\Desktop\node\bot\node_modules\request\request.js:1171:10)
>     at emitOne (events.js:115:13)
>     at Request.emit (events.js:210:7)

this is error what it gived me when offer changed. Im using this code https://pastebin.com/eh9pRYf6

**Comment by seishun** [comment]
>trade.open(toString(steamID));

What is the value of `toString(steamID)`? If it's not a decimal string, then it's not right.

**Comment by arik123** [comment]
[object undefined]

**Comment by seishun** [comment]
Well there's your problem. Consult the documentation of `steam-user` to find out how to correctly convert that object to a decimal string. `steamID.toString()` might work.

**Comment by arik123** [comment]
but when i add something it crash
