### ISSUE TITLE
addItem dont work

### ISSUE THREAD

**Issue by arik123** [seishun/node-steam-trade#81]
i used function addItem() with item defindex as partameter but it doesnt work.
What i need to put there as argument to make it work ?

**Comment by iwsfg** [comment]
Man, you should do something about how you report problems. 

First, this is not a help desk, you have been already told that and yet you're coming back again and again with more questions. The issue tracker is supposed to be used for reporting bugs in the code of the library, not in your code.

Second, this is not how you report problems with your code either. Try to provide at least some details, maybe an error you've got or some of your code, preferably formatted if you want other people to look into it.

Can you put at least some effort into looking it up yourself? The library code is only 400 lines long. [Here's the code that's using](https://github.com/seishun/node-steam-trade/blob/master/index.js#L325-L334) `item` partameter. 

Now try to figure it out yourself what it should look like

**Comment by seishun** [comment]
`addItem` takes an item from the array provided by [loadInventory](https://github.com/seishun/node-steam-trade#loadinventoryappid-contextid-callback). See the [example code](https://github.com/seishun/node-steam-trade/blob/master/scrapbank.js).

Please refrain from using the issue tracker as a helpdesk in the future, and direct your further questions to https://github.com/steam-forward/node-steam-forum.
