### ISSUE TITLE
Problem with using node-steam-trade module.

### ISSUE THREAD

**Issue by lian88jian** [seishun/node-steam-trade#82]
I'm using steam-user module for login steam and listen 'webSession' event to get sessionID and cookies, then i init node-steam-trade module with function setCookie and set sessionID. After that, i try to call open function to trade with someone, and i get {trade_status: 2, success: false} in callback. Here's part of my code, and the output in the console.
```js
var _self = this;
_self .realtrade = new SteamTrade();
_self.realtrade.sessionID = sessionID;
for(var _i in cookies){
     _self.realtrade.setCookie(cookies[_i]);
}
.......some login code
this.client.on('webSession', function (sessionID, cookies) {
    _self.realtrade.sessionID = sessionID;
    for(var _i in cookies){
        _self.realtrade.setCookie(cookies[_i]);
    }

    _trade.open('7656119806821115', function (res) {
            console.log('open callback');
            console.dir(res);
        });

    _trade.on('end', function (status, getItems) {
            console.log('end-----');
            console.log(status);
        });

        _trade.on('offerChanged', function (status, item) {
            console.log('offerChanged-----');
            console.log(status);
        });
}
//output
end-----
empty
open callback
Object {trade_status: 2, success: false}
```

**Comment by lian88jian** [comment]
I have commited a issue in node-steam-forum, but nobody gave a suggestion...

**Comment by seishun** [comment]
You can't just open a trade. See the [docs](https://github.com/seishun/node-steam-trade#opensteamid-callback):

>The trade handshake must have completed at this point - in node-steam, listen for a sessionStarted event.

I don't know how to initiate a trade in node-steam-user, but it should probably be described in their docs.

**Comment by lian88jian** [comment]
If i can send a trade to somebody with the node-steam-user module, does it mean the trade handshake has completed?

**Comment by seishun** [comment]
If they have accepted the trade, then yes.
