### ISSUE TITLE
Adding multiple items of one type

### ISSUE THREAD

**Issue by escept** [seishun/node-steam-trade#85]
I'm sorry for creating this many issues and i don't even know if this is the right place for questions like these, but can you give me an example of adding all of your items that contains a string in the name? For the past 4 hours i couldn't figure it out..

**Comment by seishun** [comment]
Try asking in https://github.com/steam-forward/node-steam-forum.

**Comment by escept** [comment]
The problem is i don't really see a reply on these posts. Whatever, i'll see tomorrow.
