### ISSUE TITLE
confirm not working sometimes

### ISSUE THREAD

**Issue by escept** [seishun/node-steam-trade#86]
steamTrade.confirm is a hit or miss for me.
```
steamTrade.on('ready', function() {
	steamTrade.ready();
	steamTrade.confirm();
	partnerready = 1;
});
```
what am i doing wrong?

**Comment by seishun** [comment]
You're not using the callback as mentioned in the docs:

>Presses the big blue "ready" button. Again, use the callback if you want to confirm as well.
